### ISSUE TITLE
Error installing Rocks 7

### ISSUE THREAD

**Issue by gabriel-milan** [rocksclusters/kernel#3]
Everytime I try to install it on the frontend machine it crashes right after it fails download e2fsprogs file.

**Comment by JVAQUEROM** [comment]
@gabriel-milan I am having similar issue (see [my email in the email list](https://marc.info/?l=npaci-rocks-discussion&m=159404151410264&w=4)). Did you managed to solve the error?

**Comment by gabriel-milan** [comment]
@JVAQUEROM no, I did not. Rocks community seems pretty dead. I've also tried PelicanHPC and similar stuff, but ended up setting an HPC cluster using [SLURM](https://slurm.schedmd.com/) (I've wrote [a guide](https://github.com/gabriel-milan/slurm-cluster) to myself after I did that) and a "services cluster" using [Rancher](https://rancher.com/). Both SLURM and Rancher are awesome softwares and I do recommend them.
